apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: my-namespace
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql-pod
      namespace: my-namespace
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql:8
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql_db
        volumeMounts:
        - name: mysql-vol
          mountPath: "/var/lib/mysql"
      volumes:
      - name: mysql-vol
        persistentVolumeClaim:
          claimName: my-pvc
